### ISSUE TITLE
Hammer

### ISSUE THREAD

**Issue by myulbok** [leagueofcake/Project-Resistance-Feedback#1]
Hammer icon (rook) is too similar in size to Person icon as a result, the Hammer can be easily mistaken as the one being picked on a mission.

Suggestions? (turnus, myulbok, shawn, domo)

> Bold the 'approve' button when it's the hammer round
> Notification (prompt, server message, action box)
> Rook icon moved into chatbox via server message

**Comment by leagueofcake** [comment]
Hammer icon changed to open star, made smaller.
